name: Run tests on dev branch

on:
  push:
    branches:
      - dev

jobs:
  run-tests-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Pip install packages
        run: |
          python -m pip install -U pip
          pip install --no-cache-dir domino-py[cli]

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pip list
        run: pip list | grep domino

      - name: Run organize and build images
        run: |
          domino piece organize --build-images --source-url=https://github.com/${{github.repository}}

      - name: Install Tests Dependencies
        run: pip install -r requirements-tests.txt

      - name: Run tests over built images
        run: |
          pytest
